#!/bin/bash

# Clean reorganization script that creates a proper manufacturer-based structure
# without duplications and with exact line mapping

echo "Creating clean manufacturer-based reorganization..."

# Start fresh with header content only (lines 1-189 contain header, legend, and TOC)
sed -n '1,189p' README_original.md > README_clean.md

# Add proper Table of Contents with manufacturer organization
cat >> README_clean.md << 'EOL'

## Table of Contents

- [Awesome Emulators](#awesome-emulators)
  - [Source Availability](#source-availability)
  - [Platform Support](#platform-support)
  - [Table of Contents](#table-of-contents)
  - [Nintendo](#nintendo)
    - [Nintendo Entertainment System/Famicom](#nintendo-entertainment-systemfamicom)
    - [Super Nintendo Entertainment System/Super Famicom](#super-nintendo-entertainment-systemsuper-famicom)
    - [Nintendo 64](#nintendo-64)
    - [Nintendo GameCube](#nintendo-gamecube)
    - [Nintendo Wii](#nintendo-wii)
    - [Nintendo Wii U](#nintendo-wii-u)
    - [Nintendo Switch](#nintendo-switch)
    - [Nintendo Switch 2](#nintendo-switch-2)
    - [Nintendo Game Boy/Game Boy Color](#nintendo-game-boygame-boy-color)
    - [Nintendo Game Boy Advance](#nintendo-game-boy-advance)
    - [Nintendo Game And Watch simulators](#nintendo-game-and-watch-simulators)
    - [Nintendo Virtual Boy](#nintendo-virtual-boy)
    - [Nintendo DS](#nintendo-ds)
    - [Nintendo 3DS](#nintendo-3ds)
  - [Sony](#sony)
    - [Sony PlayStation 1](#sony-playstation-1)
    - [Sony PlayStation 2](#sony-playstation-2)
    - [Sony PlayStation 3](#sony-playstation-3)
    - [Sony PlayStation 4](#sony-playstation-4)
    - [Sony PlayStation 5](#sony-playstation-5)
    - [Sony PlayStation Portable](#sony-playstation-portable)
    - [Sony PocketStation](#sony-pocketstation)
    - [Sony PlayStation Vita](#sony-playstation-vita)
  - [Sega](#sega)
    - [Sega Master System](#sega-master-system)
    - [Sega Genesis/Megadrive and 32X/Sega CD](#sega-genesismegadrive-and-32xsega-cd)
    - [Sega Saturn](#sega-saturn)
    - [Sega Dreamcast](#sega-dreamcast)
    - [Sega Dreamcast VMU](#sega-dreamcast-vmu)
    - [Sega Game Gear](#sega-game-gear)
  - [Microsoft](#microsoft)
    - [Microsoft Xbox](#microsoft-xbox)
    - [Microsoft Xbox 360](#microsoft-xbox-360)
    - [Microsoft Xbox One](#microsoft-xbox-one)
    - [Microsoft Xbox Series](#microsoft-xbox-series)
  - [Atari](#atari)
    - [Atari 2600](#atari-2600)
    - [Atari 5200](#atari-5200)
    - [Atari 7800](#atari-7800)
    - [Atari Jaguar/Jaguar CD](#atari-jaguarjaguar-cd)
    - [Atari Lynx](#atari-lynx)
    - [Atari 400/800 and ST computers](#atari-400800-and-st-computers)
  - [Apple](#apple)
    - [Apple computers](#apple-computers)
    - [Apple/Bandai Pippin](#applebandai-pippin)
    - [Apple iOS/iPod](#apple-iosipod)
  - [Commodore](#commodore)
    - [Commodore computers](#commodore-computers)
    - [Commodore Amiga computers/Commodore Amiga CD32](#commodore-amiga-computerscommodore-amiga-cd32)
  - [NEC](#nec)
    - [NEC PC Engine/TurboGrafx](#nec-pc-engineturbografx)
    - [NEC 6000 computers](#nec-6000-computers)
    - [NEC 8800 computers](#nec-8800-computers)
    - [NEC 9800 computers](#nec-9800-computers)
  - [SNK](#snk)
    - [SNK Neo Geo AES/MVS/Neo Geo CD](#snk-neo-geo-aesmvsneo-geo-cd)
    - [SNK Neo Geo Pocket/Color](#snk-neo-geo-pocketcolor)
  - [Texas Instruments](#texas-instruments)
    - [TI-81 series](#ti-81-series)
    - [TI-83 / TI-84 series](#ti-83--ti-84-series)
    - [TI-85 and TI-86 series](#ti-85-and-ti-86-series)
    - [TI-89 series](#ti-89-series)
    - [TI-90 series](#ti-90-series)
    - [Misc TI calculator emulators](#misc-ti-calculator-emulators)
    - [TI-Nspire](#ti-nspire)
  - [Hewlett Packard](#hewlett-packard)
    - [Hewlett Packard monochrome calculators](#hewlett-packard-monochrome-calculators)
    - [Hewlett Packard Prime calculators](#hewlett-packard-prime-calculators)
    - [Hewlett Packard scientific and financial calculators](#hewlett-packard-scientific-and-financial-calculators)
    - [Other HP calculator resources](#other-hp-calculator-resources)
  - [Casio](#casio)
    - [Casio calculators](#casio-calculators)
  - [Sharp](#sharp)
    - [Sharp calculators](#sharp-calculators)
    - [Sharp X1 computers](#sharp-x1-computers)
    - [Sharp X68000 computers](#sharp-x68000-computers)
  - [Sinclair](#sinclair)
    - [Sinclair ZX81 computers](#sinclair-zx81-computers)
    - [Sinclair ZX Spectrum computers](#sinclair-zx-spectrum-computers)
  - [Acorn](#acorn)
    - [Acorn Atom computers](#acorn-atom-computers)
    - [Acorn BBC Micro computers](#acorn-bbc-micro-computers)
    - [Acorn Electron computers](#acorn-electron-computers)
    - [Acorn Archimedes computers](#acorn-archimedes-computers)
  - [Panasonic](#panasonic)
    - [Panasonic 3DO Interactive Multiplayer](#panasonic-3do-interactive-multiplayer)
    - [Panasonic 3DO M2](#panasonic-3do-m2)
  - [Bandai](#bandai)
    - [Bandai WonderSwan/WonderSwan Color/SwanCrystal/WonderWitch](#bandai-wonderswanwonderswan-colorswancrystalwonderwitch)
  - [Game Park](#game-park)
    - [Game Park GP32](#game-park-gp32)
  - [Mattel](#mattel)
    - [Mattel Intellivision](#mattel-intellivision)
    - [Mattel HyperScan](#mattel-hyperscan)
  - [Coleco](#coleco)
    - [Coleco ColecoVision](#coleco-colecovision)
    - [Coleco computers](#coleco-computers)
  - [Magnavox](#magnavox)
    - [Magnavox Odyssey 2](#magnavox-odyssey-2)
  - [Philips](#philips)
    - [Philips CD-i](#philips-cd-i)
  - [GCE](#gce)
    - [GCE Vectrex](#gce-vectrex)
  - [VTech](#vtech)
    - [VTech V.Smile](#vtech-vsmile)
  - [Elektronika](#elektronika)
    - [Elektronika calculators](#elektronika-calculators)
  - [Watara](#watara)
    - [Watara SuperVision](#watara-supervision)
  - [Pokemon Mini](#pokemon-mini)
  - [Gemei](#gemei)
    - [Gemei A330](#gemei-a330)
  - [LaserDisc systems](#laserdisc-systems)
  - [Pong consoles](#pong-consoles)
  - [Chip-8 and related system emulators/interpreters](#chip-8-and-related-system-emulatorsinterpreters)
  - [COSMAC VIP/RCA Studio II/Telmac 1800](#cosmac-viprca-studio-iitelmac-1800)
  - [Phones/PDAs/other mobile devices, etc](#phonespdasother-mobile-devices-etc)
    - [Google Android](#google-android)
    - [N-Gage](#n-gage)
    - [BREW](#brew)
    - [Mophun](#mophun)
    - [Java](#java)
    - [Palm devices](#palm-devices)
  - [DOS emulators](#dos-emulators)
  - [x86 emulators](#x86-emulators)
  - [System/370, ESA/390, z/Architecture](#system370-esa390-zarchitecture)
  - [NeXT computers](#next-computers)
  - [Oberon RISC machine](#oberon-risc-machine)
  - [SIMH simulators](#simh-simulators)
  - [MSX computers](#msx-computers)
  - [Virtualization solutions](#virtualization-solutions)
  - [Interpreters](#interpreters)
  - [Other miscellaneous emulators and projects](#other-miscellaneous-emulators-and-projects)
    - [Adobe Flash emulators](#adobe-flash-emulators)
    - [Game engine emulators/interpreters](#game-engine-emulatorsinterpreters)
    - [Nuon emulators](#nuon-emulators)
    - [Game client emulators](#game-client-emulators)
    - [Arcade machine emulators](#arcade-machine-emulators)
    - [Pinball machine emulators](#pinball-machine-emulators)
    - [Multi-system emulators](#multi-system-emulators)
  - [Emulation platforms](#emulation-platforms)
    - [Emulation operating systems for computers](#emulation-operating-systems-for-computers)
    - [Emulation operating systems for single board computers](#emulation-operating-systems-for-single-board-computers)
    - [Emulation frontends and launchers for desktop](#emulation-frontends-and-launchers-for-desktop)
    - [Emulation frontends for mobile](#emulation-frontends-for-mobile)
    - [Game client frontends for mobile](#game-client-frontends-for-mobile)
    - [Emulation scripts for setting up multiple emulators](#emulation-scripts-for-setting-up-multiple-emulators)
    - [Emulation services](#emulation-services)
    - [Game collection managers](#game-collection-managers)
  - [👨‍💻 Contributing](#-contributing)
  - [💬 Support](#-support)
  - [🙏 Special Thanks](#-special-thanks)
  - [🐢 Author](#-author)
  - [🔗 Links](#-links)
  - [Related projects](#related-projects)
  - [Disclaimer](#disclaimer)
  - [📃 License](#-license)

EOL

echo "Header and TOC added. Now adding manufacturer content systematically..."

# Function to add content with proper heading adjustment
add_section() {
    local start_line=$1
    local end_line=$2
    local header_title="$3"
    local header_level="$4"
    
    if [ -n "$header_title" ]; then
        echo "" >> README_clean.md
        printf "%s %s\n" "$header_level" "$header_title" >> README_clean.md
        echo "" >> README_clean.md
    fi
    
    sed -n "${start_line},${end_line}p" README_original.md | sed 's/^####/###/g' | sed 's/^###\([^#]\)/### \1/g' >> README_clean.md
}

# Nintendo - Consoles (354-553) + Handhelds (867-1030)
add_section 354 553 "Nintendo" "##"
# Add Nintendo handhelds (skip the "Nintendo Handhelds" header, go directly to systems)
sed -n '869,1030p' README_original.md | sed 's/^####/###/g' >> README_clean.md

echo "Clean reorganization completed successfully."